server:
  port: 8084

spring:
  application:
    name: point-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://210.109.62.155:3306/point_db
    username: dev2
    password: dev2test
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka